// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLe5jthok8lMONNh4SnsgUZTEh6TKkTA4',
    appId: '1:227114254458:web:36fb6fbd56c48fff087bc3',
    messagingSenderId: '227114254458',
    projectId: 'duara-977ea',
    authDomain: 'duara-977ea.firebaseapp.com',
    storageBucket: 'duara-977ea.appspot.com',
    measurementId: 'G-3QMYRSXDND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaIRq5AjTNi-Xfsa01VQhT6PcpvSl-KkA',
    appId: '1:227114254458:android:a4e3c8f05e346662087bc3',
    messagingSenderId: '227114254458',
    projectId: 'duara-977ea',
    storageBucket: 'duara-977ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE6ioWRiTN-2k3vbjLFiG3A6nxn0vmfWw',
    appId: '1:227114254458:ios:f216e692b7371692087bc3',
    messagingSenderId: '227114254458',
    projectId: 'duara-977ea',
    storageBucket: 'duara-977ea.appspot.com',
    iosBundleId: 'com.example.rIntel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE6ioWRiTN-2k3vbjLFiG3A6nxn0vmfWw',
    appId: '1:227114254458:ios:5ea1e21bcad8e6cc087bc3',
    messagingSenderId: '227114254458',
    projectId: 'duara-977ea',
    storageBucket: 'duara-977ea.appspot.com',
    iosBundleId: 'com.example.rIntel.RunnerTests',
  );
}
